config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  get "/members", to: "members#index"
  
  # membersの基本ルート設定
  resources :members
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "welcome#index"
  root "members#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  # presence必須項目
  validates :name, :grade, :classroom, :age, :committee,  presence: { message: "必須項目です" }
  # validates :team, inclusion: { in: ["は組", "い組", "ろ組"] }
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all # Memberモデルの全レコードを取得してインスタンス変数に格納

    # 学年でフィルタ
    if params[:grade].present? #値が「nilでない」「存在するか？」を判定
      @members = @members.where(grade: params[:grade])
    end

    # 組でフィルタ
    if params[:classroom].present?
      @members = @members.where(classroom: params[:classroom])
    end

    # 委員会でフィルタ
    if params[:committee].present?
      @members = @members.where(committee: params[:committee])
    end
  end
  
  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to members_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @member = Member.find(params[:id])
  end
  
  def update
    @member = Member.find(params[:id])

    if @member.update(member_params)
      redirect_to members_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
   @member = Member.find(params[:id])
   
    if @member.destroy
      redirect_to members_path
    end
  end

  private
  def member_params # スコープ内で使うパラメータ定義
    params.require(:member).permit(:name, :grade, :classroom, :age, :committee, :text)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @message = "This massage from WelcomeController"
    @time = Time.now.strftime("%A, %B %d, %Y %H:%M:%S")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) + " | FirstApp": "FirstApp"%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%# Viewからの指定CSS %>
    <%= yield :stylesheets %>
    
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/edit.html.erb
<!-- app/views/members/edit.html.erb -->
<h1>Members#edit</h1>

<%= form_with model: @member, local: true do |form| %>
  <% if @member.errors.any? %>
    <div>
      <h2><%= pluralize(@member.errors.count, "Error") %>が発生しました:</h2>
      <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "名前" %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :grade, "学年" %><br>
    <%= form.select :grade, [[1, 1],[2, 2],[3, 3],[4, 4],[5, 5],[6, 6]], include_blank: "選択してください" %>
  </div>

  <div>
    <%= form.label :classroom, "組" %><br>
    <%= form.select :classroom, Member.distinct.pluck(:classroom), include_blank: "選択してください" %>
  </div>

  <div>
    <%= form.label :age, "年齢" %><br>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :committee, "委員会" %><br>
    <%= form.select :committee, [
      ["会計委員会", "会計委員会"],
      ["作法委員会", "作法委員会"],
      ["図書委員会", "図書委員会"],
      ["生物委員会", "生物委員会"],
      ["体育委員会", "体育委員会"],
      ["保健委員会", "保健委員会"],
      ["用具委員会", "用具委員会"],
      ["火薬委員会", "火薬委員会"],
      ["学級委員長委員会", "学級委員長委員会"],
    ], include_blank: "選択してください" %>
  </div>

  <div>
    <%= form.label :text, "説明" %><br>
    <%= form.text_field :text %>
  </div>

  <div>
      <%= button_to "修正", { action: "edit" }, method: :get %>
 </div>
<% end %>

app/views/members/index.html.erb
<%# CSS読み込み %>
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "members/index", "data-turbo-track": "reload" %>
<% end %>

<%# タイトル表示 %>
<% content_for :title do %>
   Member
<% end %>

<h1>Members#index</h1>
<p>Find me in app/views/members/index.html.erb</p>

<p><%= link_to "新規キャラクター登録", new_member_path %></p>

<%= form_with url: members_path, method: :get, local: true do |form| %>
<!-- form_withは非同期通信を行うメソッド、local: trueと引数を渡す事で通常のHTTPリクエストになる -->

  <div>
    <%= form.label :grade, "学年で絞り込み" %>
    <%= form.select :grade, options_for_select(Member.distinct.pluck(:grade), params[:grade]), include_blank: "すべて" %>
  </div>
  <div>
    <%= form.label :classroom, "組で絞り込み" %>
    <%= form.select :classroom, options_for_select(Member.distinct.pluck(:classroom), params[:classroom]), include_blank: "すべて" %>
  </div>
  <div>
    <%= form.label :committee, "委員会で絞り込み" %>
    <%= form.select :committee, options_for_select(Member.distinct.pluck(:committee), params[:committee]), include_blank: "すべて" %>
  </div>
  <%= form.submit "絞り込む" %><!-- パラメータにテキスト表示されるのでHTML調整 -->
<% end %>

<!-- <%= debug @members %> -->
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>名前</th>
      <th>学年</th>
      <th>組</th>
      <th>年齢</th>
      <th>委員会</th>
      <th>説明</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.id %></td>
        <td><%= member.name %></td>
        <td><%= member.grade %>年</td>
        <td><%= member.classroom %>組</td>
        <td><%= member.age %>歳</td>
        <td><%= member.committee %></td>
        <td><%= member.text %></td>
        <td>
          <%= link_to "修正", edit_member_path(member) %>
          <%= link_to "削除", member_path(member), data: {turbo_method: :delete, turbo_confirm: '本当に削除しますか？'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/new.html.erb
<!-- app/views/members/new.html.erb -->
<h1>Members#new</h1>

<%= form_with model: @member, local: true do |form| %>
  <% if @member.errors.any? %>
    <div>
      <h2><%= pluralize(@member.errors.count, "Error") %>が発生しました:</h2>
      <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "名前" %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :grade, "学年" %><br>
    <%= form.select :grade, [[1, 1],[2, 2],[3, 3],[4, 4],[5, 5],[6, 6]], include_blank: "選択してください" %>
  </div>

  <div>
    <%= form.label :classroom, "組" %><br>
    <%= form.select :classroom, [["い", "い"],["ろ", "ろ"],["は", "は"]], include_blank: "選択してください" %>
  </div>

  <div>
    <%= form.label :age, "年齢" %><br>
    <%= form.number_field :age %>
  </div>
  
  <div>
    <%= form.label :committee, "委員会" %><br>
    <%= form.text_field :committee %>
  </div>

  <div>
    <%= form.label :text, "説明" %><br>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit "登録" %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<%# CSS読み込み %>
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "welcome/index", "data-turbo-track": "reload" %>
<% end %>

<%# タイトル表示%>
<% content_for :title do %>
   Index
<% end %>

<%
  hoge = "This msg from view"
%>

<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<div class="welcome">
  <h2><%= @message %></h2>
  <p>Today's date and time is: <%= @time %></p>
  <p><%= hoge %></p>
</div>